apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mylb
  labels: 
    app: myapp
    env: dev
  namespace: devnamespace
  annotations:
    kubernetes.io/change-cause: "electric"
spec:
  minReadySeconds: 6
  replicas: 4
  selector:
    matchLabels:
      app: mylb
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template: 
    metadata:
      labels:
        app: mylb
      name: mylb-pod
    spec: 
      containers:
        - name: mylb-con
          image: hemanth65/hemanth-electricimage
          ports:
            - name: yellowapp-ports
              containerPort: 80
              protocol: TCP
          startupProbe: 
            httpGet:
              path: "/"
              port: 80
          livenessProbe:
            tcpSocket:
              port: 80
          readinessProbe:
            exec:
              command:
                - echo hi
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
           